version: '2.10'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    # environment:
    #   - VIRTUAL_HOST=letsventure.ml,jenkins.letsventure.ml,grafana.letsventure.ml
    #   - VIRTUAL_PORT=3000,8080,3333

  # Jenkins
  docker:
    image: docker:dind
    container_name: jenkins_docker
    restart: always
    privileged: true
    networks:
      jenkins:
        aliases:
          - docker
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    ports:
      - "127.0.0.1:2376:2376"

  jenkins:
    image: jenkinsci/blueocean:latest
    container_name: jenkins_blueocean
    restart: always
    depends_on:
      - docker
    networks:
      - jenkins
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
      VIRTUAL_HOST: jenkins.letsventure.ml
      VIRTUAL_PORT: 8080
    volumes:
      - jenkins-docker-certs:/certs/client:ro
      - jenkins-data:/var/jenkins_home
    ports:
      - "127.0.0.1:8080:8080"
      # - "127.0.0.1:50000:50000"

volumes:
  jenkins-docker-certs:
  jenkins-data:

networks:
  jenkins:

  # End of Jenkins

  # webserver:
  #   image: jwilder/whoami
  #   expose:
  #     - "3000"
  #   environment:
  #     - VIRTUAL_HOST=letsventure.ml
  #     - VIRTUAL_PORT=3000
